---
###
## This package will install Apache
#

- name: Install Apache
  yum:
    name: httpd
    state: present
  notify: Restart httpd

- name: Start the Apache Service
  service:
    name: httpd
    enabled: true
    state: started
